language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
cache:
    directories:
        - $HOME/.cache/pip
install:
    - pip install --upgrade pip setuptools wheel
    - pip install -r .requirements-full-test.txt --only-binary=numpy,scipy
script:
    - py.test test/
